### ISSUE TITLE
Cannot restart; rebuilding folders does not fix

### ISSUE THREAD

**Issue by rspivack** [Colorado4Wheeler/HomeKit-Bridge#101]
HomeKit Bridge Attempting to start 'HomeKitBridge'

Apr 9, 2018 at 12:11:58 PM
HomeKit Bridge Error HomeKit server 'HomeKitBridge' could not be started, please check the service logs for more information,
now issuing a forced shutdown of the service to be safe.

If you continue to have problems starting this server use the Advanced Plugin Actions menu option to rebuild the Homebridge folder.
Instructions at https://github.com/Colorado4Wheeler/Hom ... dge-folder
HomeKit Bridge Attempting to stop 'HomeKitBridge'
HomeKit Bridge HomeKit server 'HomeKitBridge' has been stopped
HomeKit Bridge Error send "HomeKitBridge" on failed

**Comment by Colorado4Wheeler** [comment]
As I had mentioned in the forums, please use the advanced plugin actions menu option to output your Homebridge log and config.

**Comment by Colorado4Wheeler** [comment]
Those messages are for Homebridge, which is interesting.  That would point to one of three things that I can think of:

- The Homebridge is corrupt, thus a bad download of the plugin, removing and re-installing the plugin might solve that
- There is a problem with the camera portion, the same solution as the first bullet, but I don't think it's a bug because too many folks are using the camera portion
- A file system problem

I would download the plugin again and copy and paste it over what you have there now, in case it's a bad download.  That kind of issue, if it were a bug, would have reared its ugly head many, MANY, times by now so I'm 99.9% certain it's not a bug.

**Comment by rspivack** [comment]
I manually deleted the plugin file in the Indigo applications directory tree and downloaded it again.  Now it is starting up, so this issue can be closed out.

Not sure about the corruption, I thought the zip file and subsequent handling would insure consistency, but I guess that is a macOS issue somewhere along the line and not specific to the plugin or Indigo.

Might be worth putting a notice in the FAQ or docs as you indicated this has happened to other people and the plugin file is rather large so maybe more susceptible to corruption than typical plugins.
