### ISSUE TITLE
Nest thermostats showing degrees in the 160-170F range.

### ISSUE THREAD

**Issue by VolKnox** [Colorado4Wheeler/HomeKit-Bridge#114]
Upon adding three Nest units to the Homebridge, Homekit shows them just fine, but all reading temps in the 160-170F range.  I can control the units, but temps are way off.

Running Version 1.0.2 FINAL

First post here so forgive any omissions.

**Comment by Colorado4Wheeler** [comment]
You didn't set the option when you added the thermostats that the temperatures are in Fahrenheit, so it is not converting the temperature to Celsius and so when, say, 70 degrees is sent to HomeKit and it It thinks that it is 70 degrees Celsius it shows you the temperature as 158 degrees Fahrenheit because your HomeKit is set to show you your temps in F.

Edit the device, check the box that says that the thermostat temperature is F and you should be fine.

**Comment by VolKnox** [comment]
Thank you.  I did as you said and it worked.  Just missed that step.

Thanks
