### ISSUE TITLE
Loading Accessories and Scenes

### ISSUE THREAD

**Issue by durosity** [Colorado4Wheeler/HomeKit-Bridge#58]
I don't think this is actually HKB related as it seems to just be due to a long standing iOS bug, but i felt i should document this anyway just in case it's something of relevance.  

Yesterday i managed to get the message above which if you duckduckgo it you'll see lots of reports of over the years.  There's various different theories on what cause it, most of which centre around the keychain.  I tried all the steps as per the guides listed but no joy.  Had to reset the configuration and set everything up again, which of course was a pain but at least HBK's ability to set custom names and such made the whole process a lot easier!  

I had the issue in this circumstance:

I was at work with my phone connected using a reasonable 4G connection
I was using TeamViewer to connect to my server at home
I edited one of the devices in a "Misc" HKB device i have setup for action groups, saved it and the change applied to my phone.  I then went back and changed another one and no change appeared that i was aware of, but after a couple of mins i suddenly got the dreaded "Loading Accessories and Scenes".  This affected ALL homekit devices including non HBK items (So a Hue Hub was also unavailable).  In Elgato's Eve app it'd open and show my devices but with warning symbols next to all of them including the Hues.  I tried restarting HBK just in case that helped but no joy.  I tried the keychain and other steps others had tried but no joy, restarted phone, etc.  When i got home i tried it again but still the same and also looked at my iPad and it was having the same issue.  Interestingly though i was still getting notifications from devices about the security alarm being disabled and the front door being unlocked.  

Unfortunately i couldn't find a resolve and had to delete the home and set it up again.  I've tried to replicate it but couldn't.

**Comment by Colorado4Wheeler** [comment]
There are a few things that seem to blow up the HomeKit database.  It's calmed down quite a bit but I had a similar issue a few weeks ago, however I hadn't had any kind of blowup for over a year before that.  

What I generally do when I have an issue is first switch to a second home, even if you create a blank one just for the sake of switching to it, then switch back then often that primes the pump and gets things working again.  Because I'm in and out of 8 homes on my apps for testing HKB I've found this to be nearly 100% reliable when HomeKit seems to hang.  If the HomeKit database blows up, though, not much to do about that other than start again.

It would be interesting, however, to create a second home and put a few devices in it and see if that home also dies when HomeKit blows up.  I have one I call "Administrative" that I use for sort of this purpose, it's where I put things that I just don't want cluttering up my main HomeKit home - it's also a convenient place to switch back and forth from when things hang up - I would be interested if switching to a fully configured second home and back would bring things back to life.  Maybe that's why I have had so few problems over the past year, multiple home configs.

**Comment by durosity** [comment]
Yeah i tried the second home trick but alas no joy.  However that is an interesting idea, i think i'll create a second home just with some dummy devices just to see if it happens again.  I hope not though.. having to assign devices to rooms, assign some types (eg the afore mentioned windows and doors) and modify some names and such is just a pain.  Wishlist feature for iOS 12:  Automatic room assignments!  Oh and a backup and restore option for homekit databases.  Not that Apple will ever do that!
