### ISSUE TITLE
Why HB-Indigo1 thermostat shows green and HB-Indigo2 shows red

### ISSUE THREAD

**Issue by Colorado4Wheeler** [Colorado4Wheeler/HomeKit-Bridge#6]
Normal HK operation shows the thermostat current temperature in orange when  heating and blue when cooling, why did HBI1 show it as blue?

**Comment by webdeck** [comment]
The way I interpreted it, Characteristic.CurrentHeatingCoolingState is only supposed to be set to HEAT or COOL when your heater or AC is running - otherwise it should be OFF.  It's only supposed to show red if your furnace is on at the moment, blue if your AC is running, green if neither (green as in "current temp is fine, no need to heat or cool.")

**Comment by Colorado4Wheeler** [comment]
Thanks :).
