### ISSUE TITLE
After reload HKB the Home.app freezes

### ISSUE THREAD

**Issue by IndigoVaillant** [Colorado4Wheeler/HomeKit-Bridge#68]
When doing a reload of the plugin or after a stop/start (save Configure HomeKit Accessory Server), the Home app freezes. Just before it freezes I see thermostats grey out en become -1.0 and the state of a virtual device changes from closed to open.

Putting the app in the back ground and selecting it again or restarting the app unfreezes it. The thermostats come back on and the virtual device changes from open to closed to reflect the correct state.

Is this expected behaviour?

**Comment by Colorado4Wheeler** [comment]
Yes it is, and it's not the plugin.  Home does that, especially after you restart HomeKit Bridge because HomeKit is constantly polling and when you restart there's an interruption and everything goes wonky for a moment.  My solution to that is to create a second home and simply switch to that home and back and that will speed things up.  You can also kill Home and re-open it.  It will snap back on it's own but think about if you had opened a file on a network drive and lost your network, the app would probably beachball for a moment while it re-establishes and then all is well.

**Comment by IndigoVaillant** [comment]
Expected as much. Thanks for clearing that up.

One thing does not seem right to me and that is how the virtual device is handled when there is a interruption. In my case the virtual device is defined with a Garage Door Opener as HomeKit Type. I had to invert the on/off state to get the right status displayed in de Home.app. 

It seems that when there is an interruption the **default state** of a device is displayed in the Home.app. In my case the state 'closed' changes to 'open' on interrupted communication. When communication is restablished the state is changed to 'closed' again. Problem with this is that the Home.app handels this state change as an actual change. In my case I get a notification that the garage is closed (but no notification that the garage was opened before).

If this is expected behaviour too I must rethink how to use the option to invert the state in HKB because the consequences could be unexpected. Think about (alarm)sensors that could be getting a state change due to a restart and trigger something.

**Comment by Colorado4Wheeler** [comment]
The Home app is smart enough to know that it's not talking to the accessory, there should be no false positives when in this state, those default values are just sanity checks for the HomeKit data so if it can't talk to something and shows a default state of "open", for example, it knows that it's not really "open" until confirmed.

**Comment by IndigoVaillant** [comment]
Problem is that in this case the false positive does get handled by the Home.app as a real state change. I have it set up to get notifications on change of state. I do get a notification on this false positive (i.e. when the state changes to closed).

**Comment by Colorado4Wheeler** [comment]
I'm not sure you get notifications on false positives, I do not and as many times as I reload my Home as I do development then I would have noticed by now if my smoke sensors went off.  This may have to do with how the virtual group is set up because one thing that I had to turn off because it was driving me nuts when I reloaded was I had a CO sensor device as a test that was always on, so when the device wasn't loading and actually talked to Indigo I would get the notification "CO Levels High in Room" notice.  I point that out specifically because it's always in a true state and I **only** got notified of it when it finally talked to Indigo because it defaulted to a false state.

**Comment by Colorado4Wheeler** [comment]
Typo "I'm not sure you get notifications" should be "I'm not sure WHY you get notifications"

**Comment by IndigoVaillant** [comment]
berkinet had the exact same problem.
http://forums.indigodomo.com/viewtopic.php?f=201&t=20340&start=120#p157183

> And, my gate control. I have created a Virtual Device that operates a momentary contact Action to control the gate. To track the state of the gate, I have a variable setup. Its value is either open or closed. The Virtual Device interprets closed as off and open as on. Basically, I am simulating successive presses on a single button remote control. In HKB I have selected the Virtual Device as a Garage Door and called it the gate and set the state as inverted. In general it works, except, whenever I restart HKB, the gate in HK changes its state to open, even though the Virtual Device is off and the gate is closed. I used the garage door so I can say "open the gate" I think the HK service should startup in the right state but can't seem to get it to do that.

**Comment by Colorado4Wheeler** [comment]
Please do a device simulation on both the open and closed state so I can see what the values are.

**Comment by IndigoVaillant** [comment]
[closed.txt](https://github.com/Colorado4Wheeler/HomeKit-Bridge/files/1836925/closed.txt)
[open.txt](https://github.com/Colorado4Wheeler/HomeKit-Bridge/files/1836926/open.txt)
