### ISSUE TITLE
Minor only - Camera Settings / Debug only sticking with restart of Plugin

### ISSUE THREAD

**Issue by Ghawken** [Colorado4Wheeler/HomeKit-Bridge#75]
Thanks

**Comment by Colorado4Wheeler** [comment]
Yes I'm aware, that's why that's in the instructions that you need to restart your camera plugin devices if you change the settings 😉.  It's either that or come up with a convoluted method of going through ever server impacted by the change and restart them, which only happens if I track the initial settings first, which means capturing it before the dialog is open and stashing it separately.....  So, as you can see, I had zero desire to spend an hour coding for the sake of telling someone to just restart the device.  You shouldn't have to restart the plugin, I didn't, only the devices with cameras.

**Comment by Colorado4Wheeler** [comment]
Added to the next release.
