### ISSUE TITLE
Notifications Reset for devices 

### ISSUE THREAD

**Issue by Ghawken** [Colorado4Wheeler/HomeKit-Bridge#84]
Hi,

I have noticed that it appears under certain conditions notifications for a particular device are reset?  Anyone else seen this?  Initially thought is was with HomeKit server restarting - but now can't reproduce it....

eg. - turn off notifications for device (seems to default to on) for Locks
At some later time - get notification and check device - and notification is back on for this device.  Still trying to check what causes this to occur.

Dropping WAF considerably....Might be more a homebridge issue though I wonder?

Thanks

**Comment by durosity** [comment]
I’ve had this occasionally too, and it seems to be related to any scenes I create disappearing.  Have you set any scenes up including these devices?

**Comment by Colorado4Wheeler** [comment]
I don't think it's a Homebridge issue, but it's possible I suppose.  I suspect it's collisions with the data.  I have half a dozen iPods, several iPhones and 4 Apple TV 4's that are all batting that data around and I think that eventually they collide on an accessory.

Just the other day the majority of my devices - but not all - lost their room config, notification settings and favorite setting.  I'm pretty sure Homebridge didn't do that because I know it can't even touch rooms and am 99% sure it cannot touch the rest.  What I noticed, though, is that the problem impacted only one of my servers, and it's my most used and changed one.  I can't help but to wonder if having it open on my phone and tablet while I was constantly restarting the server or leaving it down for hours on end while I tested code changes had anything to do with it.    That took me an hour to get my stuff back in order, proved to me that I need to spread the device around servers more.

**Comment by Colorado4Wheeler** [comment]
You know, I had to re-read this to really have it hit me what you were saying but, yes, my notifications checkbox keeps getting turned on too, it's pretty frustrating because in my testing it's not unusual for me to have 3-4 of the same lock or garage door spread across devices as I'm working on things and POOF I'll get 8-10 notifications because the garage just closed and auto locked my door and I got back in and, yup, all the notifications are back on again.  I'll tag this with @webdeck to see if there might be something going on in HB that is doing this that he may be able to control.

**Comment by webdeck** [comment]
Notifications all happen on the iOS side - there is no way to control them from the HomeKit API.  Are notifications getting turned back on at the same time as when devices are losing their rooms, or is it happening independently of that?

**Comment by Colorado4Wheeler** [comment]
For me, yes, it happens then most certainly but I believe it happens without losing rooms too.  I’ll try to keep better track.

**Comment by webdeck** [comment]
Please see if your homebridge log contains the line:

Created 0 accessories

If that's there, then I think I have a workaround for it.

**Comment by Colorado4Wheeler** [comment]
This issue seems to have been resolved as I haven't seen any issue since @webdeck put in failsafes against 'zero device' Homebridge loads.
