### ISSUE TITLE
Duplicated cameras

### ISSUE THREAD

**Issue by webdeck** [Colorado4Wheeler/HomeKit-Bridge#94]
I upgraded from 0.21 to 0.22 and now I have two copies of my cameras in the Home app - one set that works, and one that shows a broken camera icon.

The broken cameras show Manufacturer as "Indigo HomeKit Bridge" with a Serial Number that is probably the device ID since it's a long hex string, and Model as "N/A".  The broken cameras wound up in the "Misc" room.

The working cameras show Manufacturer as "Default-Manufacturer" Serial Number as "Default-SerialNumber" and Model as "Default-Model".  The working cameras retained their room assignments.

Both sets of cameras say they belong to the same bridge.

**Comment by webdeck** [comment]
config.json shows only one set of cameras configured, as does the config of the bridge in Indigo.

**Comment by webdeck** [comment]
And the config.json is identical to the last backup I have, except for the description which has a different date/time of when it was generated...  so this seems to be a HomeKit / homebridge / homebridge-camera-ffmpeg issue

**Comment by Colorado4Wheeler** [comment]
Disable the enhancements, I just realized why that’s happening.

**Comment by Colorado4Wheeler** [comment]
I’ll patch it for tomorrow.

**Comment by webdeck** [comment]
That fixed it.

**Comment by Colorado4Wheeler** [comment]
Yea, when I rewrote that I left out letting the camera pass as a device.  It really should have only happened if you also had other devices in addition to the camera since the configuration builder is supposed to exclude the HB-Indigo2 platform if there are nothing but cameras.  On my system where I have my cameras isolated on their own server that didn't happen.

This issue is resolved in the upcoming revision.
